fixed typos and improved OS X stuff

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -43,7 +43,7 @@ setup_gitconfig () {
 }
 
 setup_irssi_config () {
-  if ! [ -f irssi/config ]
+  if ! [ -f irssi/irssi.symlink/config ]
   then
     info 'setup irssiconfig'
 
@@ -81,7 +81,7 @@ install_dotfiles () {
 
       if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
       then
-        user "File already exists: ${dest}, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
+        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
         read -n 1 action
 
         case "$action" in
@@ -133,8 +133,27 @@ setup_irssi_config
 install_dotfiles
 
 # If we are on a mac, lets install and setup homebrew
-if [ "$(uname -s)" == "Darwinn" ]
+if [ "$(uname -s)" == "Darwin" ]
 then
+  info "Setting up OS X preferences, which requires sudo access.\n"
+  $ZSH/osx/set-defaults.sh
+  info "Note that some of these changes require a logout/restart to take effect.\n"
+
+  if test ! $(which brew); then
+    user ' - Homebrew is not installed! Would you like to install it? (y/n) '
+    read -e reply
+    if [[ $reply =~ ^[Yy]$ ]]; then
+      info "installing brew"
+      ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
+      if test ! $(which brew); then
+        fail "error installing brew"
+        exit 1
+      else
+        success "brew installed"
+      fi
+    fi
+  fi
+
   info "installing dependencies"
   if . bin/dot > /tmp/dotfiles-dot 2>&1
   then
